task_type: 'train'
model: 'custom'
img_dir: 'Data/custom/full'
train_csv_path: 'Data/custom/train.csv'
val_csv_path: 'Data/custom/val.csv'
resize: [155,200]
crop_size: Null
num_epochs: 30
batch_size: 32
batch_loss: 100
early_stopping_rounds: 6
model_save_dir: 'models'
training_loss_graph_path: 'reports/figures/custom2.png'
learning_rate: 3e-4